config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|sv/ do
    resources :imports
    resources :scores, :rounds, :tour_parts, :tees, :holes, :courses, :competitions, :clubs, :users, :statistics

    get 'sessions/new'

    root :to => "pages#index"
    get '/users'    => 'users#index'
    get '/signup'   => 'users#new'
    get '/login'    => 'sessions#new'
    post '/login'   => 'sessions#create'
    delete '/logout'=> 'sessions#destroy'

    get '/admin'              => 'admins#index'
    get '/admin/users'        => 'admins#users'
    get '/admin/clubs'        => 'admins#clubs'
    get '/admin/competitions' => 'admins#competitions'
    get '/admin/courses'      => 'admins#courses'
    get '/admin/tees'         => 'admins#tees'
    get '/admin/user/new'     => 'admins#create_player'
    get '/admin/round'        => 'admins#rounds'
    get '/admin/tours'        => 'admins#tours'
    get '/admin/imports'      => 'admins#imports'
    post '/scores/update'     => 'scores#update'

    get '/course/statistics'      => 'courses#statistics'

    get '/competition/statistics' => 'competitions#statistics'
    get '/competition/records'    => 'competitions#records'
    get '/competition/tours'      => 'competitions#tours'
    get '/statistics/headtohead/' => 'statistics#headtohead'
    get '/competition/totals'     => 'competitions#totals'
    get '/tour_part_line_chart'   => 'tour_parts#line_chart'
    get '/import_tour_part'       => 'imports#import_tour_part'

    get 'stats'   => 'statistics#index'
    get 'hole_stats' => 'statistics#hole_stats'

    get 'import' => 'tour_parts#import_tour_part'
  end
end

app/views/admins/clubs.html.haml
%header.masthead
  .container
    .row.page_header.admin
      .col-md-4
        %h1 Klubbar

      .col-md-8#leftCol
        %ul.nav.nav-tabs.pull-right
          %li
            = link_to (fa_icon "plus", text: "Ny klubb"), new_club_path

    .row.spacing
      = render :partial => 'admins/partials/menu'

      .col-md-10
        %table.table.table-hover
          %thead
            %th Namn
            %th
          %tbody
            - @clubs.each do |u|
              %tr
                %td= u.name
                %td
                  = link_to "", edit_club_path(u), class: "glyphicon glyphicon-pencil"

app/views/admins/competitions.html.haml
%header.masthead
  .container
    .row.page_header.admin
      .col-md-4
        %h1 Tävlingar

      .col-md-8#leftCol
        %ul.nav.nav-tabs.pull-right
          %li
            = link_to (fa_icon "plus", text: "Ny tävling"), new_competition_path

    .row.spacing
      = render :partial => 'admins/partials/menu'

      .col-md-10
        %table.table.table-hover
          %thead
            %th Namn
            %th
          %tbody
            - @competitions.each do |u|
              %tr
                %td= u.name
                %td
                  = link_to "", edit_competition_path(u), class: "glyphicon glyphicon-pencil"

app/views/admins/courses.html.haml
%header.masthead
  .container
    .row.page_header.admin
      .col-md-4
        %h1 Banor

      .col-md-8#leftCol
        %ul.nav.nav-tabs.pull-right
          %li
            = link_to (fa_icon "plus", text: "Ny bana"), new_course_path

    .row.spacing
      = render :partial => 'admins/partials/menu'

      .col-md-10
        %table.table.table-hover
          %thead
            %th Namn
            %th Klubb
            %th Antal hål
            %th Tee(s)
            %th Actions
          %tbody
            - @courses.each do |u|
              %tr
                %td= link_to u.name, course_path(u)
                %td= u.club.name
                %td= u.holes
                %td
                  - u.tees.each do |t|
                    = t.color
                %td
                  = link_to "", edit_course_path(u), class: "glyphicon glyphicon-pencil"
                  = link_to "", new_tee_path, class: "glyphicon glyphicon-plus"

app/views/admins/imports.haml
%header.masthead
  .container
    .row.page_header.admin
      .col-md-6
        %h1 Importer

    .row.spacing
      = render :partial => 'admins/partials/menu'

      .col-md-10
        %table.table.table-hover
          %thead
            %th Tävling
            %th Namn
            %th Klubb
            %th File
            %th Actions
          %tbody
            - @imports.each do |i|
              %tr
                %td= i.comp_name
                %td= i.tour_name
                %td= i.club
                %td= link_to "Ladda ner fil", i.import_sheet_url
                %td
                  = link_to "", import_tour_part_path(id: i), class: "glyphicon glyphicon-plus"
                  = link_to "", import_path(i), method: :delete, class: 'glyphicon glyphicon-trash'

app/views/admins/index.html.haml
.container
  .row.page_header.admin
    .col-md-6
      %h1 Kontrollpanel

  .row.spacing
    = render :partial => 'admins/partials/menu'

  .row.spacing

app/views/admins/rounds.html.haml
%header.masthead
  .container
    .row.page_header.admin
      .col-md-4
        %h1 Rundor
        = link_to 'New Round', new_round_path

      .col-md-8#leftCol
        %ul.nav.nav-tabs.pull-right
          %li
            = link_to (fa_icon "plus", text: "Ny runda"), new_round_path

    .row.spacing
      = render :partial => 'admins/partials/menu'

      .col-md-10
        - @tour_parts.each do |tour|
          %table.table.table-hover
            %thead
              %th Datum
              %th Spelare
              %th Bana
              %th Resultat
              %th Score?
              %th
            %tbody
              - tour.rounds.each do |r|
                %tr
                  %td= r.tour_part.date.strftime("%Y-%m-%d")
                  %td= r.user.name
                  %td= "#{r.course.name} - #{r.tee.color}"
                  %td= r.total
                  %td
                    = link_to "", new_score_path(r.id), class: 'glyphicon glyphicon-plus'
                  %td
                    = link_to "", round_path(r), class: "glyphicon glyphicon-user"
                    = link_to "", edit_score_path(r), class: "glyphicon glyphicon-pencil"
                    = link_to "", round_path(r), method: :delete, class: 'glyphicon glyphicon-trash'

        .text-center
          = will_paginate @tour_parts

app/views/admins/tees.html.haml
%header.masthead
  .container
    .row.page_header.admin
      .col-md-4
        %h1 Teepads

      .col-md-8#leftCol
        %ul.nav.nav-tabs.pull-right
          %li
            = link_to (fa_icon "plus", text: "Ny tee"), new_tee_path

    .row.spacing
      = render :partial => 'admins/partials/menu'

      .col-md-10
        %table.table.table-hover
          %thead
            %th Färg
            %th Bana
            %th Antal hål
            %th Actions
          %tbody
            - @tees.each do |t|
              %tr
                %td= link_to t.color, tee_path(t)
                %td= t.course.name
                %td= t.holes.count
                %td
                  = link_to "", edit_tee_path(t), class: "glyphicon glyphicon-pencil"
                  = link_to "", new_hole_path, class: "glyphicon glyphicon-plus"

app/views/admins/tours.html.haml
%header.masthead
  .container
    .row.page_header.admin
      .col-md-4
        %h1 Deltävlingar

      .col-md-8#leftCol
        %ul.nav.nav-tabs.pull-right
          %li
            = link_to (fa_icon "plus", text: "Ny deltävling"), new_tour_part_path

    .row.spacing
      = render :partial => 'admins/partials/menu'

      .col-md-10
        %table.table.table-hover
          %thead
            %th Namn
            %th Tävling
            %th Tee
            %th Datum
            %th Lägg till runda
            %th
          %tbody
            - @tour_parts.each do |u|
              %tr
                %td= u.name
                %td= link_to u.competition.name, competition_path(u.competition)
                %td= u.tee.color
                %td= u.date.strftime("%Y-%m-%d")
                %td= link_to "Lägg till", new_round_path(id: u)
                %td
                  = link_to "", edit_tour_part_path(u), class: "glyphicon glyphicon-pencil"
                  = link_to "", tour_part_path(u), method: :delete, class: 'glyphicon glyphicon-trash'

        .text-center
          = will_paginate @tour_parts

app/views/admins/users.html.haml
%header.masthead
  .container
    .row.page_header.admin
      .col-md-4
        %h1 Användare

      .col-md-8#leftCol
        %ul.nav.nav-tabs.pull-right
          %li
            = link_to (fa_icon "plus", text: "Ny användare"), new_user_path

    .row.spacing
      = render :partial => 'admins/partials/menu'

      .col-md-10
        %table.table.table-hover
          %thead
            %th Namn
            %th PDGA #
            %th Division
            %th Email
            %th Klubb
            %th
          %tbody
            - @users.each do |u|
              %tr
                %td= u.name
                %td= "##{u.pdga}"
                %td= u.division
                %td= u.email
                %td= u.club.name
                %td
                  = link_to "", user_path(u), class: "glyphicon glyphicon-user"
                  = link_to "", edit_user_path(u), class: "glyphicon glyphicon-pencil"

        .text-center
          = will_paginate @users