config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|sv/ do
    resources :imports
    resources :scores, :rounds, :tour_parts, :tees, :holes, :courses, :competitions, :clubs, :users, :statistics

    get 'sessions/new'

    root :to => "pages#index"
    get '/users'    => 'users#index'
    get '/signup'   => 'users#new'
    get '/login'    => 'sessions#new'
    post '/login'   => 'sessions#create'
    delete '/logout'=> 'sessions#destroy'

    get '/admin'              => 'admins#index'
    get '/admin/users'        => 'admins#users'
    get '/admin/clubs'        => 'admins#clubs'
    get '/admin/competitions' => 'admins#competitions'
    get '/admin/courses'      => 'admins#courses'
    get '/admin/tees'         => 'admins#tees'
    get '/admin/user/new'     => 'admins#create_player'
    get '/admin/round'        => 'admins#rounds'
    get '/admin/tours'        => 'admins#tours'
    get '/admin/imports'      => 'admins#imports'
    post '/scores/update'     => 'scores#update'

    get '/course/statistics'      => 'courses#statistics'

    get '/competition/statistics' => 'competitions#statistics'
    get '/competition/records'    => 'competitions#records'
    get '/competition/tours'      => 'competitions#tours'
    get '/statistics/headtohead/' => 'statistics#headtohead'
    get '/competition/totals'     => 'competitions#totals'
    get '/tour_part_line_chart'   => 'tour_parts#line_chart'
    get '/import_tour_part'       => 'imports#import_tour_part'

    get 'stats'   => 'statistics#index'
    get 'hole_stats' => 'statistics#hole_stats'

    get 'import' => 'tour_parts#import_tour_part'
  end
end

app/models/hole.rb
class Hole < ActiveRecord::Base

  belongs_to :tee
  has_many :scores

  scope :tour_part_hole_avg, -> (id) {
    select("holes.*, ROUND(SUM(s.score)/COUNT(s.id), 2) as avg").
    joins("INNER JOIN scores s on holes.id = s.hole_id").
    where("s.tour_part_id = #{id}").
    group("holes.number")
  }

  scope :competition_hole_avg, -> (id) {
    select("holes.*, ROUND(SUM(s.score)/COUNT(s.id), 2) as avg").
    joins("INNER JOIN scores s on holes.id = s.hole_id").
    where("s.competition_id = #{id}").
    group("holes.number")
  }

  scope :hole_stats, -> (id) {
    select("holes.*").
    where("holes.id = #{id}")
  }

end

app/controllers/holes_controller.rb
class HolesController < ApplicationController
  before_action :set_hole, only: [:show, :edit, :update, :destroy]
  before_filter :stats

  def stats
    @stats ||= Stats::StatsCommon.new
    @stats
  end

  # GET /holes
  # GET /holes.json
  def index
    @holes = Hole.all
  end

  # GET /holes/1
  # GET /holes/1.json
  def show
    @holes = Hole.where(tee_id: @hole.tee_id).order(:number)
    @graphs = stats.graph_types
    @graph_type = params[:graph] || "spline"
    @data_type = params[:data_type] || "result"
    @course = Course.find(@hole.course_id)
    @tee = Tee.find(@hole.tee_id)

    if @data_type == "user"
      data = Score.hole_result_stats(@hole.id).by_user(current_user.id).group_by_result
      results = stats.get_hole_result_stats(data)
    else
      data = Score.hole_result_stats(@hole.id).group_by_result
      results = stats.get_hole_result_stats(data)
    end

    result_types = stats.get_result_types(data)
    @chart = stats.build_hole_chart(@hole.number, results, @graph_type, result_types)
  end

  # GET /holes/new
  def new
    @hole = Hole.new
  end

  # GET /holes/1/edit
  def edit
  end

  # POST /holes
  # POST /holes.json
  def create
    @hole = Hole.new(hole_params)

    respond_to do |format|
      if @hole.save
        format.html { redirect_to tee_path(@hole.tee_id), notice: 'Hole was successfully created.' }
        format.json { render :show, status: :created, location: @hole }
      else
        format.html { render :new }
        format.json { render json: @hole.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holes/1
  # PATCH/PUT /holes/1.json
  def update
    respond_to do |format|
      if @hole.update(hole_params)
        format.html { redirect_to @hole, notice: 'Hole was successfully updated.' }
        format.json { render :show, status: :ok, location: @hole }
      else
        format.html { render :edit }
        format.json { render json: @hole.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holes/1
  # DELETE /holes/1.json
  def destroy
    @hole.destroy
    respond_to do |format|
      format.html { redirect_to holes_url, notice: 'Hole was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hole
      @hole = Hole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hole_params
      params.require(:hole).permit(:course_id, :number, :par, :length, :tee_id)
    end
end

app/helpers/holes_helper.rb
module HolesHelper
end

app/views/holes/_form.html.haml
= form_for(@hole) do |f|
  -if @hole.errors.any?
    .error_explanation
      %ul
        = @hole.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.collection_select(:course_id, Course.all, :id, :name, class: 'form-control')
  .form-group
    = f.number_field :number, placeholder: 'nummer', class: 'form-control'
  .form-group
    = f.number_field :par, placeholder: 'par', class: 'form-control'
  .form-group
    = f.number_field :length, placeholder: 'längd', class: 'form-control'
  .form-group
    = f.collection_select(:tee_id, Tee.all, :id, :color, class: 'form-control')
  .form-group
    = f.submit :Spara, class: 'btn btn-sm btn-primary'

app/views/holes/edit.html.erb
<h1>Editing Hole</h1>

<%= render 'form' %>

<%= link_to 'Show', @hole %> |
<%= link_to 'Back', holes_path %>

app/views/holes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Holes</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Number</th>
      <th>Par</th>
      <th>Length</th>
      <th>Tee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holes.each do |hole| %>
      <tr>
        <td><%= hole.course_id %></td>
        <td><%= hole.number %></td>
        <td><%= hole.par %></td>
        <td><%= hole.length %></td>
        <td><%= hole.tee_id %></td>
        <td><%= link_to 'Show', hole %></td>
        <td><%= link_to 'Edit', edit_hole_path(hole) %></td>
        <td><%= link_to 'Destroy', hole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hole', new_hole_path %>

app/views/holes/new.html.erb
<h1>New Hole</h1>

<%= render 'form' %>

<%= link_to 'Back', holes_path %>

app/views/holes/show.haml
.container
  .row.spacing
    .col-md-12
      %table.table.table-hover
        %tbody
          %tr
            %td Nr
            - @holes.each do |hole|
              %td= link_to hole.number, hole_path(id: hole, data_type: @data_type, graph: @graph_type), class: @hole.id == hole.id ? 'active' : ''
            %tr
              %td= t(:Length)
              - @holes.each do |hole|
                %td= link_to "#{hole.length} m", hole_path(id: hole, data_type: @data_type, graph: @graph_type), class: @hole.id == hole.id ? 'active' : ''

            %tr
              %td= t(:Par)
              - @holes.each do |hole|
                %td= link_to hole.par, hole_path(id: hole, data_type: @data_type, graph: @graph_type), class: @hole.id == hole.id ? 'active' : ''

    .col-md-12
      .col-md-12.charts
        = link_to t(:All_players), hole_path(id: @hole.id, graph: @graph_type, data_type: "result"), class: "pull-left graph-button #{@data_type == "result" ? 'active' : ''}"
        = link_to (fa_icon "user"), hole_path(id: @hole.id, graph: @graph_type, data_type: "user"), class: "pull-left graph-button #{@data_type == "user" ? 'active' : ''}"
        - @graphs.each do |graph|
          = link_to fa_icon(graph.last), hole_path(id: @hole.id, graph: graph.first, data_type: @data_type), class: "pull-right graph-button #{graph.first == @graph_type ? 'active' : ''}"
        .col-md-12{id: "line_chart"}
          = high_chart("line_chart", @chart)
  .row.spacing