config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|sv/ do
    resources :imports
    resources :scores, :rounds, :tour_parts, :tees, :holes, :courses, :competitions, :clubs, :users, :statistics

    get 'sessions/new'

    root :to => "pages#index"
    get '/users'    => 'users#index'
    get '/signup'   => 'users#new'
    get '/login'    => 'sessions#new'
    post '/login'   => 'sessions#create'
    delete '/logout'=> 'sessions#destroy'

    get '/admin'              => 'admins#index'
    get '/admin/users'        => 'admins#users'
    get '/admin/clubs'        => 'admins#clubs'
    get '/admin/competitions' => 'admins#competitions'
    get '/admin/courses'      => 'admins#courses'
    get '/admin/tees'         => 'admins#tees'
    get '/admin/user/new'     => 'admins#create_player'
    get '/admin/round'        => 'admins#rounds'
    get '/admin/tours'        => 'admins#tours'
    get '/admin/imports'      => 'admins#imports'
    post '/scores/update'     => 'scores#update'

    get '/course/statistics'      => 'courses#statistics'

    get '/competition/statistics' => 'competitions#statistics'
    get '/competition/records'    => 'competitions#records'
    get '/competition/tours'      => 'competitions#tours'
    get '/statistics/headtohead/' => 'statistics#headtohead'
    get '/competition/totals'     => 'competitions#totals'
    get '/tour_part_line_chart'   => 'tour_parts#line_chart'
    get '/import_tour_part'       => 'imports#import_tour_part'

    get 'stats'   => 'statistics#index'
    get 'hole_stats' => 'statistics#hole_stats'

    get 'import' => 'tour_parts#import_tour_part'
  end
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  acts_as_taggable
  acts_as_taggable_on :tags

  belongs_to :club
  has_many :tour_parts
  has_many :scores

  scope :by_name, -> {order(name: :asc)}
  scope :latest, -> {order(updated_at: :desc)}
  scope :search, -> (term) { where("name LIKE '%#{term}%'") }

end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]
  before_filter :stats
  require 'set'
  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
    @search = params[:term] || nil
    if @search
      @competitions = Competition.search(@search)
      @tags = Competition.tagged_with(@search)
    else
      @competitions = @competitions.paginate(:page => params[:page], :per_page => 10)
    end

  end

  def stats
    @stats ||= Stats::StatsCommon.new
    @stats
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    @competition = Competition.where(id: params[:id]).first
    @page_title = t(:Home)
    @heading = @competition.name
    @tags = @competition.tags
  end

  def records
    @page_title = t(:Record_rounds)
    @heading = t(:Record_rounds)
    @competition = Competition.find(params[:id])
    @tees = Tee.where(id: @competition.tour_parts.map(&:tee_id)).includes(:rounds, :holes)
    rounds = Round.bogeyfree_rounds.from_competition(@competition.id).group_by_round
    @bogeyfree_rounds = stats.bogeyfree_rounds(rounds)
  end

  def tours
    @competition = Competition.where(id: params[:id]).first
    @page_title = t(:Tour_parts)
    @heading = @competition.name
    @tour_parts = TourPart.where(competition_id: params[:id]).order("date DESC").includes(:course, :tee, :rounds)
    @tour_parts = @tour_parts.paginate(:page => params[:page], :per_page => 10)
  end

  def totals
    @page_title = t(:Overall_standings)
    @heading = t(:Overall_standings)
    @competition = Competition.find(params[:id])
    @users = Round.competition_players(params[:id])
  end

  def statistics
    @page_title = t(:Statistics)
    @heading = t(:Statistics)
    @graph_type = params[:graph] || "spline"
    @data_type = params[:data_type] || "avg"
    @competition = Competition.find(params[:id])
    @all_scores = Score.where(competition_id: params[:id]).includes(:hole)
    @tour_parts = TourPart.where(competition_id: params[:id]).by_date
    @graphs = stats.graph_types

    if params[:tour_part]
      @tour_part = TourPart.find(params[:tour_part])
    else
      @tour_part = @tour_parts.first
    end
    @date = params[:date] || @tour_part.date

    @months = Hash.new()
    months = TourPart.group_by_month(@tour_part.id, @competition.id)
    months.each_with_index do |month, index|
      tours = TourPart.by_competition_and_date(@competition.id, month.date.strftime("%m").to_i)
      @months[month.date] = tours
    end
    @tee = Tee.find(@tour_part.tee_id)
    @holes = Hole.where(tee_id: @tee.id)

    if @data_type == "avg"
      numbers = stats.holes(@holes) # gets the hole numbers
      round = Round.where(tour_part_id: @tour_part.id, tee_id: @tee.id, place: 1).order("total ASC").limit(1) # gets the lowest score for the competition
      scores = Score.where(tour_part_id: @tour_part.id).includes(:hole)
      avg = Score.tour_part_avg(@tour_part.id) # gets average score for line graph
      avg = stats.tour_part_avg_score(avg)
      all_avg = Score.competition_avg(@competition.id, @tee.id)
      all_avg  = stats.tour_part_avg_score(all_avg)
      totals = stats.numbers(scores)

      check = Round.where(user_id: current_user.id, tour_part_id: @tour_part.id).first if current_user
      @headtohead = true if check

      if @headtohead
        head_scores = Score.where(user_id: current_user.id, tour_part_id: @tour_part.id)
        data = head_scores.map(&:score).to_a
        @chart = stats.tour_part_line_chart(@tour_part, numbers, @tee.color, data, @graph_type, avg, all_avg)
      else
        @chart = stats.tour_part_line_chart(@tour_part, numbers, @tee.color, @graph_type, avg, all_avg)
      end
    else
      @chart = stats.hole_bar_chart(@graph_type, @holes, @tour_part, @tee.color)
    end
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:name, :title, :content, :club_id, :date, :tag_list)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.haml
.row
  = form_for(@competition) do |f|
    .col-md-4
      .form-group
        = f.text_field :name, placeholder: "namn", class: 'form-control'
      .form-group
        = f.text_field :title, placeholder: "titel", class: 'form-control'
      .form-group
        = f.text_area :content, placeholder: "beskrivning", class: 'form-control'
      .form-group
        = f.collection_select(:club_id, Club.all, :id, :name, class: 'form-control')
      .form-group
        = f.datetime_select :date, class: 'form-control'
      .form-group
        = f.label :tag_list, "Tags (separated by commas)"
        = f.text_field :tag_list
      .form-group
        = f.submit :Spara, class: 'btn btn-sm btn-primary'

app/views/competitions/edit.html.haml
.container
  .row
    .col-md-12
      %h1= "Redigera tävling #{@competition.name}"

  = render 'form'

app/views/competitions/index.haml
%header.masthead
  .container
    .row.spacing.page_header.normal
      .col-md-8
        %h1
          = t(:Tournaments)
        - if @search
          %small
            = "Visar sökresultat för '#{@search}' - "
            = link_to "Visa alla", competitions_path
        - else
          %small= t(:All_shown, resource: t(:Tournaments).downcase)

    .row.spacing
      .col-md-12
        .input-group
          = form_tag competitions_path, method: :get do
            = text_field_tag :term, @search, size: 32, placeholder: t(:Search_resource, resource: t(:Tournaments).downcase), class: "form-control"
          %span.input-group-btn
            = submit_tag t(:Search), type: "button", class: "btn btn-primary"

    .row.spacing
      - @competitions.each do |comp|
        .col-md-4
          .event
            .col-md-3
              = fa_icon "trophy", class: "fa-4x padding-icon"
            .col-md-9
              %ul
                %li
                  %h5
                    = link_to comp.name, competition_path(comp.id)
                %li= fa_icon "calendar", class: "fa-1x", text: comp.date.strftime("%Y-%m-%d")

    - if @tags
      .row
        .col-md-12
          %p
            = "Visar sökresultat taggad med"
            %span.tag= @search
      .row
        - @tags.each do |comp|
          .col-md-4
            .event
              .col-md-3
                = fa_icon "trophy", class: "fa-4x padding-icon"
              .col-md-9
                %ul
                  %li
                    %h5
                      = link_to comp.name, competition_path(comp.id)
                  %li= fa_icon "calendar", class: "fa-1x", text: comp.date.strftime("%Y-%m-%d")

app/views/competitions/new.haml
.container
  .row
    .col-md-4
      %h1 Ny Tävling
  = render 'form'

app/views/competitions/records.haml
.container
  - @tees.each do |tee|
    .row
      .col-md-12
        %h2.highlight= "#{t(:Record_rounds)} - #{tee.color} tee"
        %table.table.table-hover
          %tbody
            %tr
              %td Nr
              - tee.holes.each do |h|
                %td= h.number
            %tr
              %td= t(:Length)
              - tee.holes.each do |h|
                %td= h.length

            %tr
              - tee.rounds.limit(20).each do |r|
                %tr
                  %td
                    = link_to r.user.name, user_path(r.user.id)

                  - r.scores.each do |s|
                    %td{class: "#{s.result_type} #{get_ob_stroke(s.ob)} text-center"}= s.score
                  %td= calc_score(r.total, r.tee.par)
  .row.spacing
    - unless @bogeyfree_rounds.blank?
      .col-md-12
        %h2.highlight= t(:bogeyfree_rounds)
        %table.table.table-hover
          %tbody
            %tr
              %td= t(:Name)
              %td Tee
              - @tees.first.holes.each do |h|
                %td= h.number
          - @bogeyfree_rounds.each do |round|
            %tr
              %td= round.user.name
              %td= round.tee.color
              - round.scores.each do |s|
                %td{class: "#{s.result_type} #{get_ob_stroke(s.ob)} text-center"}= "#{s.score}"
              %td= calc_score(round.total, round.tee.par)

app/views/competitions/show.html.haml
.container
  .row
    .col-md-5
      %h2.highlight= t(:Tags)
      = render :partial => '/shared/partials/tags', locales: {tags: @tags}

  .row.spacing

app/views/competitions/statistics.haml
.container
  .row.spacing
    .col-md-3
      %ul.list-group
        %li.list-group-item
          %span.badge
            = @competition.tour_parts.count
          = @competition.name
        - @months.each_with_index do |month, index|
          %li.list-group-item
            = link_to month.first.strftime("%B %Y"), "#collapseSideMenu-#{index}", role: :button, data: { toggle: "collapse", target: "#collapseSideMenu-#{index}" }, aria: { controls: "collapseSideMenu-#{index}", expanded: "false" }

          %div.tours{class: @date.to_date.strftime("%B %Y") == month.first.strftime("%B %Y") ? 'collapse in' : 'collapse', id: "collapseSideMenu-#{index}"}
            - month.last.each do |tour|
              %li.list-group-item
                %span.badge= tour.date.strftime("%Y-%m-%d")
                = link_to tour.name, competition_statistics_path(id: @competition.id, tour_part: tour.id, graph: @graph_type, data_type: @data_type, date: tour.date), class: "#{tour.id == @tour_part.id ? 'active' : ''}"
    .col-md-9
      .col-md-12.charts
        = link_to t(:Avg_result), competition_statistics_path(id: @competition.id, tour_part: @tour_part.id, graph: @graph_type, data_type: "avg"), class: "pull-left graph-button #{@data_type == "avg" ? 'active' : ''}"
        = link_to t(:Result), competition_statistics_path(id: @competition.id, tour_part: @tour_part.id, graph: @graph_type, data_type: "result"), class: "pull-left graph-button #{@data_type == "result" ? 'active' : ''}"
        - @graphs.each do |graph|
          = link_to fa_icon(graph.last), competition_statistics_path(id: @competition.id, tour_part: @tour_part.id, graph: graph.first, data_type: @data_type), class: "pull-right graph-button #{graph.first == @graph_type ? 'active' : ''}"
        .col-md-12{id: "line_chart"}
          = high_chart("line_chart", @chart)
  .row.spacing

app/views/competitions/totals.haml
.container
  .row
    .col-md-5
      %h2.highlight= t(:Players)
      %table.table.table-hover
        %thead
          %th= t(:Name)
          %th= t(:Club)
          %th= t(:Tour_parts)
        %tbody
          - @users.each do |user|
            %tr
              %td= user.name
              %td= user.club_name
              %td= "#{user.rounds_count} #{t(:St)}"

app/views/competitions/tours.haml
.container
  .row
    .col-md-7
      %h2.highlight= t(:Tour_parts)
      %table.table.table-hover
        %thead
          %th= t(:Name)
          %th= t(:Date)
          %th= t(:Course)
          %th= t(:Players)
        %tbody
          - @tour_parts.each do |tour|
            %tr{data: {href: tour_part_path(tour)}}
              %td= link_to tour.name, tour_part_path(tour)
              %td= tour.date.strftime("%Y-%m-%d")
              %td= "#{tour.course.name} - #{tour.tee.color}"
              %td= "#{tour.rounds.count} #{t(:St)}"

    .row.text-center
      .col-md-7
        = will_paginate @tour_parts