config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|sv/ do
    resources :imports
    resources :scores, :rounds, :tour_parts, :tees, :holes, :courses, :competitions, :clubs, :users, :statistics

    get 'sessions/new'

    root :to => "pages#index"
    get '/users'    => 'users#index'
    get '/signup'   => 'users#new'
    get '/login'    => 'sessions#new'
    post '/login'   => 'sessions#create'
    delete '/logout'=> 'sessions#destroy'

    get '/admin'              => 'admins#index'
    get '/admin/users'        => 'admins#users'
    get '/admin/clubs'        => 'admins#clubs'
    get '/admin/competitions' => 'admins#competitions'
    get '/admin/courses'      => 'admins#courses'
    get '/admin/tees'         => 'admins#tees'
    get '/admin/user/new'     => 'admins#create_player'
    get '/admin/round'        => 'admins#rounds'
    get '/admin/tours'        => 'admins#tours'
    get '/admin/imports'      => 'admins#imports'
    post '/scores/update'     => 'scores#update'

    get '/course/statistics'      => 'courses#statistics'

    get '/competition/statistics' => 'competitions#statistics'
    get '/competition/records'    => 'competitions#records'
    get '/competition/tours'      => 'competitions#tours'
    get '/statistics/headtohead/' => 'statistics#headtohead'
    get '/competition/totals'     => 'competitions#totals'
    get '/tour_part_line_chart'   => 'tour_parts#line_chart'
    get '/import_tour_part'       => 'imports#import_tour_part'

    get 'stats'   => 'statistics#index'
    get 'hole_stats' => 'statistics#hole_stats'

    get 'import' => 'tour_parts#import_tour_part'
  end
end

app/views/admins/partials/_menu.haml
.col-md-2
  %ul.list-group#admin
    %li.list-group-item
      = link_to (fa_icon "users", text: "Användare"), admin_users_path
    %li.list-group-item
      = link_to (fa_icon "asterisk", text: "Klubbar"), admin_clubs_path
    %li.list-group-item
      = link_to (fa_icon "tree", text: "Banor"), admin_courses_path
    %li.list-group-item
      = link_to (fa_icon "flag", text: "Tees"), admin_tees_path
    %li.list-group-item
      = link_to (fa_icon "trophy", text: "Tävlingar"), admin_competitions_path
    %li.list-group-item
      = link_to (fa_icon "star-o", text: "Deltävlingar"), admin_tours_path
    %li.list-group-item
      = link_to (fa_icon "fire", text: "Rundor"), admin_round_path
    %li.list-group-item
      = link_to (fa_icon "users", text: "Importer"), admin_imports_path